# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: 'jazzfan1', email: 'jeff@email.com', location: 'Dallas, TX', password: '123456')
User.create(username: 'terry', email: 'terry@email.com', location: 'Houston, TX', password: '123456')
User.create(username: 'vinyldude2001', email: 'vinyldude2001@email.com', location: 'Austin, TX', password: '123456')
User.create(username: 'alex', email: 'alex@email.com', location: 'New York, NY', password: '123456')


Record.create(artist: 'Miles Davis', title: 'Bags Groove', year: 1957, record_label: "Prestige", country: "US", cat_num: "7109", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "Mono", img_url: 'https://img.discogs.com/OmcoK0X6OCW9JCu8tmexAlDLDZs=/fit-in/600x595/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2311979-1555004656-8268.jpeg.jpg', user_id: 1)
Record.create(artist: 'Sonny Rollins', title: "Saxophone Colossus", year: 1957, record_label: "Prestige", country: "US", cat_num: "7079", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/rRADHd3i9kGm5rr18FFkBgT4W3w=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-3934932-1494609907-3882.jpeg.jpg', user_id: 1)
Record.create(artist: 'Ornette Coleman', title: "The Shape of Jazz To Come", year: 1959, record_label: "Atlantic", country: "US", cat_num: "SD 1317", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://i.redd.it/7ngqfp7uqmd21.jpg', user_id: 1)
Record.create(artist: 'Jackie McLean', title: "Destination Out!", year: 1964, record_label: "Blue Note", country: "US", cat_num: "BST 84165", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/CK2nqfVpK5oDMZ4ge5VxWT59-Ug=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1189824-1327363437.jpeg.jpg', user_id: 1)
Record.create(artist: 'Pharoah Sanders', title: "Pharaoh", year: 1965, record_label: "ESP Disk", country: "US", cat_num: "1003", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/tZ_wXl7bysX7xgKOyXWEAxlEfAw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4912731-1379243459-3698.jpeg.jpg', user_id: 1)

Record.create(artist: 'Creedence Clearwater Revival', title: 'Bayou Country', year: 1969, record_label: "Fantasy", country: "US", cat_num: "8387", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/3/37/Creedence_Clearwater_Revival_-_Bayou_Country.jpg', user_id: 2)
Record.create(artist: 'Creedence Clearwater Revival', title: "Cosmo's Factory", year: 1970, record_label: "Fantasy", country: "US", cat_num: "8402", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/4/42/Creedence_Clearwater_Revival_-_Cosmo%27s_Factory.jpg', user_id: 2)
Record.create(artist: 'Creedence Clearwater Revival', title: "Green River", year: 1969, record_label: "Fantasy", country: "US", cat_num: "8393", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/0/04/Creedence_Clearwater_Revival_-_Green_River.jpg', user_id: 2)
Record.create(artist: 'Creedence Clearwater Revival', title: "Willy and The Poor Boys", year: 1969, record_label: "Fantasy", country: "US", cat_num: "8397", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/8/85/Willy_and_the_poor_boys.jpg', user_id: 2)
Record.create(artist: 'Creedence Clearwater Revival', title: "Creedence Clearwater Revival", year: 1968, record_label: "Fantasy", country: "US", cat_num: "8382", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Creedence_Clearwater_Revival_-_Creedence_Clearwater_Revival.jpg', user_id: 2)

Record.create(artist: 'Marty Robbins', title: 'Gunfighter Ballads And Trail Songs', year: 1959, record_label: "Columbia", country: "US", cat_num: "CL 1349", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/QYBLfWae8I7glLW5Yd3gVyUzlDA=/fit-in/600x598/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-13567900-1556700531-9037.jpeg.jpg', user_id: 3)
Record.create(artist: 'Can', title: "Tago Mago", year: 1971, record_label: "United Artist", country: "Germany", cat_num: "UAS 29 211/12 X", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/1MTeOdOwUvwM33wGdkvb8h1_moc=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-226132-1438201839-2876.jpeg.jpg', user_id: 3)
Record.create(artist: 'Prince', title: "Dirty Mind", year: 1980, record_label: "Warner Bros", country: "US", cat_num: "BSK 3478", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/hLjqZqLFFimWOeOCkIt-a0JHXU4=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7690671-1446822344-3754.jpeg.jpg', user_id: 3)
Record.create(artist: 'The Impressions', title: "This Is My Country", year: 1968, record_label: "Curtom", country: "US", cat_num: "CRS 8001", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/mBiA1aCbIkKk9z_CooKv27jpmlU=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-12829653-1542753031-5849.jpeg.jpg', user_id: 3)
Record.create(artist: 'Shirley and Company', title: "Shame Shame Shame", year: 1975, record_label: "Vibration", country: "US", cat_num: "VI-128", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://img.discogs.com/cRcYXYhON4bg-nxnuOTlN78DylQ=/fit-in/550x550/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2605768-1292820551.jpeg.jpg', user_id: 3)

Record.create(artist: 'Scientist', title: "Scientist Meets The Space Invaders", year: 2010, record_label: "Greensleeves", country: "US", cat_num: "GREL 19", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: "  ", img_url: "http://i.imgur.com/kOeAx6M.jpg", user_id: 4)
Record.create(artist: 'Scientist', title: "Scientist Encounters Pac-Man", year: 2012, record_label: "Greensleeves", country: "US", cat_num: "GREL 46", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: "  ", img_url: 'https://images-na.ssl-images-amazon.com/images/I/81NhshflY5L._SL1063_.jpg', user_id: 4)
Record.create(artist: 'The Fall', title: "Perverted By Language", year: 1983, record_label: "Rough Trade", country: "UK", cat_num: "ROUGH 62", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: "  ", img_url: 'https://cdn.shopify.com/s/files/1/0219/8812/products/SV127_web_1024x1024.jpg?v=1490983271', user_id: 4)
Record.create(artist: 'Swell Maps', title: "A Trip To Marineville", year: 1979, record_label: "Rough Trade", country: "UK", cat_num: "ROUGH 2", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: 'with original bonus 7"', img_url: 'https://img.discogs.com/Z_7btnMwJV7d_A4em3_S9osYL84=/fit-in/600x597/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-802562-1352280409-8936.jpeg.jpg', user_id: 4)
Record.create(artist: 'David Bowie', title: "The Man Who Sold The World", year: 1970, record_label: "Mercury", country: "US", cat_num: "SR-61325", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: '...bootleg :( ', img_url: 'https://img.discogs.com/GlrBkuxbP9lE0AUrGLQ29eyzEwY=/fit-in/600x599/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-710468-1475029886-8513.jpeg.jpg', user_id: 4)
Record.create(artist: 'Television', title: "Marquee Moon", year: 1977, record_label: "Elektra", country: "US", cat_num: "7E-1098", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: 'European pressing in US sleeve, for some reason', img_url: 'https://img.discogs.com/bZH3R0Is0qkJqbmwyDS5TjGg-HM=/fit-in/589x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-2838321-1303340982.jpeg.jpg', user_id: 4)
Record.create(artist: 'Bee Gees', title: "Odessa", year: 1969, record_label: "ATCO", country: "US", cat_num: "SD 2-702", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: 'Original double LP version in velvet sleeve', img_url: 'https://img.discogs.com/S8dTJbLdOQpCf3EIhUTREH_d6w4=/fit-in/600x588/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1930742-1382814336-5426.jpeg.jpg', user_id: 4)
Record.create(artist: 'Michael Nesmith & The First National Band', title: "Magnetic South", year: 1970, record_label: "RCA Victor", country: "US", cat_num: "LSP-4371", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: '', img_url: 'https://ia802301.us.archive.org/22/items/mbid-2edf44dc-dd93-4167-9c00-c03e2cbe9078/mbid-2edf44dc-dd93-4167-9c00-c03e2cbe9078-22193710690.jpg', user_id: 4)
Record.create(artist: 'Moby Grape', title: "Moby Grape", year: 1967, record_label: "Columbia", country: "US", cat_num: "CL 2698", format: '12"', speed: "33 rpm", disc_condition: 'VG', sleeve_condition: 'G+', description: 'Mono pressing with the infamous "finger cover"', img_url: 'https://ia803003.us.archive.org/3/items/mbid-fd9a6095-bc44-4032-86ca-e42d900e7943/mbid-fd9a6095-bc44-4032-86ca-e42d900e7943-5504426725.jpg', user_id: 4)
Record.create(artist: 'Black Sabbath', title: "Black Sabbath", year: 1970, record_label: "Warner Bros", country: "US", cat_num: "WS 1871", format: '12"', speed: "33 rpm", disc_condition: 'VG', sleeve_condition: 'VG', description: '', img_url: 'https://ia800509.us.archive.org/16/items/mbid-069dc077-63e4-3ee8-903b-0dd53cf555bf/mbid-069dc077-63e4-3ee8-903b-0dd53cf555bf-10533954155.jpg', user_id: 4)
Record.create(artist: 'The Misfits', title: "Static Age", year: 1997, record_label: "Caroline", country: "US", cat_num: "CAROL 7520-1", format: '12"', speed: "33 rpm", disc_condition: 'NM', sleeve_condition: 'VG+', description: '', img_url: 'https://img.discogs.com/A7Wd03C5CdTQOEpdr5xIuHESLrg=/fit-in/600x599/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-489145-1264605053.jpeg.jpg', user_id: 4)
Record.create(artist: 'Prince Jammy', title: "Computerised Dub", year: 2012, record_label: "Greensleeves", country: "US", cat_num: "GREL 92", format: '12"', speed: "33 rpm", disc_condition: 'NM', sleeve_condition: 'VG+', description: '', img_url: 'https://img.discogs.com/IslwGgq_J9bezb3_vfqDWZ7DtIE=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4316284-1362000185-8978.jpeg.jpg', user_id: 4)
Record.create(artist: 'Doris Norton', title: "Personal Computer", year: 2018, record_label: "Mannequin", country: "Germany", cat_num: "MNQ 120", format: '12"', speed: "33 rpm", disc_condition: 'NM', sleeve_condition: 'NM', description: 'Reissue', img_url: 'https://img.discogs.com/cDyldwfBLKTtY3FLJjHxCN-8dvY=/fit-in/600x606/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-11895306-1524308109-2471.png.jpg', user_id: 4)
Record.create(artist: 'Willaim Onyeabor', title: "Atomic Bomb", year: 2015, record_label: "Luaka Bop", country: "US", cat_num: "LBLP5033", format: '12"', speed: "33 rpm", disc_condition: 'NM', sleeve_condition: 'NM', description: 'Reissue', img_url: 'https://img.discogs.com/Zrt4RLijsfZEm3lDgwqoMqWrMQw=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7776882-1448551091-9094.jpeg.jpg', user_id: 4)
Record.create(artist: 'Rolling Stones', title: "Their Satanic Majesties Request", year: 1967, record_label: "London", country: "US", cat_num: "NPS-2", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG+', description: 'Lenticular cover', img_url: 'https://ia802508.us.archive.org/24/items/mbid-b172010e-9ba9-4d80-a8f2-9142ce94ed8b/mbid-b172010e-9ba9-4d80-a8f2-9142ce94ed8b-14746340139.jpg', user_id: 4)
Record.create(artist: 'Creedence Clearwater Revival', title: 'Bayou Country', year: 1969, record_label: "Fantasy", country: "US", cat_num: "8387", format: '12"', speed: "33 rpm", disc_condition: 'VG+', sleeve_condition: 'VG', description: "  ", img_url: 'https://upload.wikimedia.org/wikipedia/en/3/37/Creedence_Clearwater_Revival_-_Bayou_Country.jpg', user_id: 4)


